### ISSUE TITLE
Global name "keyring" is not defined

### ISSUE THREAD

**Issue by Bmarquez1997** [anoved/OctoPrint-EmailNotifier#50]
When running the yagmail.register command, I get the following message:

(username and password removed for privacy)
>>> yagmail.register("<insert username>","<insert password>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/oprint/local/lib/python2.7/site-packages/yagmail/password.py", line 37, in register
    keyring.set_password("yagmail", username, password)
NameError: global name 'keyring' is not defined

I followed the steps in the readme, first importing yagmail, and then running the register command

**Comment by slippmann** [comment]
I had to install keyring first
```
~/oprint/bin/pip install --upgrade keyring
```

I also required upgrades for pip and setuptools before keyring would successfully install
```
~/oprint/bin/pip install --upgrade pip
~/oprint/bin/pip install --upgrade setuptools
```

**Comment by aashutosh0012** [comment]
Need to install keyring
`pip install keyring`
